-- ============================================================================
--  MÓDULO VETERINARIA — Cirugías (coordinación + registro quirúrgico)
--  El agendamiento vive en `turnos` (tipo = 'Cirugía'); esta tabla guarda el
--  registro clínico de cada cirugía, que se muestra en la historia del paciente.
-- ============================================================================
CREATE TABLE IF NOT EXISTS cirugias (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint REFERENCES pacientes(id) ON DELETE SET NULL,
  cliente_id       bigint REFERENCES clientes(id)  ON DELETE SET NULL,
  turno_id         bigint REFERENCES turnos(id)    ON DELETE SET NULL,  -- turno que la originó (opcional)
  fecha            date NOT NULL DEFAULT current_date,
  estado           text NOT NULL DEFAULT 'realizada',   -- programada / realizada / cancelada
  cirujano         text,        -- quién operó
  ayudante         text,        -- quién asistió
  anestesia        text,        -- tipo/protocolo anestésico
  procedimiento    text,        -- qué cirugía (ej: OVH, castración, extracción de masa)
  diagnostico      text,
  hallazgos        text,        -- lo que se encontró durante la cirugía
  complicaciones   text,
  indicaciones     text,        -- indicaciones post-operatorias
  notas            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON cirugias;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON cirugias
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE cirugias ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON cirugias;
CREATE POLICY org_isolation ON cirugias FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON cirugias TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_cirugias_org      ON cirugias(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_cirugias_paciente ON cirugias(paciente_id);
CREATE INDEX IF NOT EXISTS idx_cirugias_fecha    ON cirugias(fecha);
CREATE INDEX IF NOT EXISTS idx_cirugias_turno    ON cirugias(turno_id);

-- Autoría automática (creado_por / actualizado_por), igual que el resto de tablas clínicas.
ALTER TABLE cirugias ADD COLUMN IF NOT EXISTS creado_por text;
ALTER TABLE cirugias ADD COLUMN IF NOT EXISTS actualizado_por text;
DROP TRIGGER IF EXISTS tg_autor ON cirugias;
CREATE TRIGGER tg_autor BEFORE INSERT OR UPDATE ON cirugias
  FOR EACH ROW EXECUTE FUNCTION tg_set_autor();
