-- ============================================================================
--  Constantes personalizadas de internación (por organización) + Pulso Femoral
-- ============================================================================

-- Catálogo de constantes que cada organización puede definir (nombre + unidad).
CREATE TABLE IF NOT EXISTS constantes_personalizadas (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  nombre           text NOT NULL,
  unidad           text,
  activo           boolean NOT NULL DEFAULT true,
  orden            int NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON constantes_personalizadas;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON constantes_personalizadas
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE constantes_personalizadas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON constantes_personalizadas;
CREATE POLICY org_isolation ON constantes_personalizadas FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON constantes_personalizadas TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_constantes_pers_org ON constantes_personalizadas(organizacion_id);

-- Pulso femoral (constante fija, pedida explícitamente) + valores de las
-- constantes personalizadas de cada control: {"Nombre": {"valor": "...", "unidad": "..."}}
ALTER TABLE internacion_registros ADD COLUMN IF NOT EXISTS pulso_femoral text;
ALTER TABLE internacion_registros ADD COLUMN IF NOT EXISTS constantes_extra jsonb;
