-- ============================================================================
--  MÓDULO VETERINARIA — Consultas / Historia clínica
-- ============================================================================

CREATE TABLE IF NOT EXISTS consultas (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
  fecha            date NOT NULL DEFAULT CURRENT_DATE,
  motivo           text,
  diagnostico      text,
  tratamiento      text,
  peso             numeric(8,2),
  temperatura      numeric(4,1),
  notas            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON consultas;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON consultas
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON consultas;
CREATE POLICY org_isolation ON consultas FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON consultas TO authenticated, service_role;

CREATE INDEX IF NOT EXISTS idx_consultas_org      ON consultas(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_consultas_paciente ON consultas(paciente_id);
