-- ============================================================================
--  MÓDULO VETERINARIA — Estudios complementarios (archivos por paciente)
-- ============================================================================

CREATE TABLE IF NOT EXISTS estudios (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
  titulo           text,
  tipo             text,
  archivo_path     text NOT NULL,    -- ruta dentro del bucket
  archivo_nombre   text,             -- nombre original del archivo
  tamano           bigint,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON estudios;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON estudios
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE estudios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON estudios;
CREATE POLICY org_isolation ON estudios FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON estudios TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_estudios_org      ON estudios(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_estudios_paciente ON estudios(paciente_id);

-- ── Bucket de Storage (privado) ──────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('estudios', 'estudios', false)
ON CONFLICT (id) DO NOTHING;

-- Aislamiento por organización: la 1ª carpeta de la ruta es el org_id
DROP POLICY IF EXISTS "estudios_select" ON storage.objects;
CREATE POLICY "estudios_select" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'estudios' AND (storage.foldername(name))[1] = get_my_org_id()::text);

DROP POLICY IF EXISTS "estudios_insert" ON storage.objects;
CREATE POLICY "estudios_insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'estudios' AND (storage.foldername(name))[1] = get_my_org_id()::text);

DROP POLICY IF EXISTS "estudios_delete" ON storage.objects;
CREATE POLICY "estudios_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'estudios' AND (storage.foldername(name))[1] = get_my_org_id()::text);
