-- ============================================================================
--  MÓDULO VETERINARIA — Internación (hospitalización) + hoja de tratamiento
-- ============================================================================
CREATE TABLE IF NOT EXISTS internaciones (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint REFERENCES pacientes(id) ON DELETE SET NULL,
  cliente_id       bigint REFERENCES clientes(id)  ON DELETE SET NULL,
  motivo           text,
  estado           text NOT NULL DEFAULT 'internado',   -- internado / alta / fallecido
  fecha_ingreso    timestamptz NOT NULL DEFAULT now(),
  fecha_egreso     timestamptz,
  notas            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON internaciones;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON internaciones
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE internaciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON internaciones;
CREATE POLICY org_isolation ON internaciones FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON internaciones TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_internaciones_org    ON internaciones(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_internaciones_estado ON internaciones(estado);

-- Registros de la hoja de internación: constantes, medicación, evolución.
CREATE TABLE IF NOT EXISTS internacion_registros (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  internacion_id   bigint REFERENCES internaciones(id) ON DELETE CASCADE,
  fecha_hora       timestamptz NOT NULL DEFAULT now(),
  tipo             text NOT NULL DEFAULT 'evolucion',   -- constante / medicacion / evolucion
  peso             numeric(8,2),
  temperatura      numeric(5,2),
  fc               int,        -- frecuencia cardiaca
  fr               int,        -- frecuencia respiratoria
  mucosas          text,
  tratamiento      text,       -- qué se aplicó / indicó
  aplicado_por     text,       -- quién lo aplicó
  nota             text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON internacion_registros;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON internacion_registros
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE internacion_registros ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON internacion_registros;
CREATE POLICY org_isolation ON internacion_registros FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON internacion_registros TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_int_reg_org ON internacion_registros(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_int_reg_int ON internacion_registros(internacion_id);
