-- Códigos de invitación: solo quien tenga un código válido (de un solo uso) puede
-- registrarse. Los maneja únicamente el service role desde las rutas /api.
CREATE TABLE IF NOT EXISTS invitaciones (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo      text UNIQUE NOT NULL,
  email       text,        -- si está, el código solo sirve para ese email
  rubro       text,        -- sugerencia de rubro (opcional)
  nota        text,        -- a quién se lo diste
  usada       boolean NOT NULL DEFAULT false,
  usada_por   text,
  usada_at    timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE invitaciones ENABLE ROW LEVEL SECURITY;
-- Sin policies: anon/authenticated no pueden leerla ni escribirla. El service_role
-- (usado solo en las rutas /api del servidor) ignora RLS.
GRANT ALL ON invitaciones TO service_role;
