-- ============================================================================
--  MÓDULO VETERINARIA — Pacientes (mascotas)
-- ============================================================================

CREATE TABLE IF NOT EXISTS pacientes (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id   uuid REFERENCES organizaciones(id),
  cliente_id        bigint REFERENCES clientes(id) ON DELETE SET NULL,  -- dueño
  nombre            text NOT NULL,
  especie           text,
  raza              text,
  sexo              text,
  fecha_nacimiento  date,
  peso              numeric(8,2),
  color             text,
  notas             text,
  activo            boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- Aislamiento por organización
DROP TRIGGER IF EXISTS tg_set_org_id ON pacientes;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON pacientes
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON pacientes;
CREATE POLICY org_isolation ON pacientes FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON pacientes TO authenticated, service_role;

CREATE INDEX IF NOT EXISTS idx_pacientes_org     ON pacientes(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_pacientes_cliente ON pacientes(cliente_id);
