-- ============================================================================
--  MÓDULO Peluquería — planilla diaria de turnos (baño, peluquería, etc.)
-- ============================================================================
CREATE TABLE IF NOT EXISTS peluqueria_turnos (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id       uuid REFERENCES organizaciones(id),
  fecha                 date NOT NULL DEFAULT current_date,
  hora                  text,
  canil                 text,
  nombre                text,        -- mascota (opcional)
  raza                  text,
  servicio              text,
  propietario_nombre    text,
  propietario_apellido  text,
  propietario_telefono  text,
  precio                numeric(12,2),
  observaciones         text,
  created_at            timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON peluqueria_turnos;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON peluqueria_turnos
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE peluqueria_turnos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON peluqueria_turnos;
CREATE POLICY org_isolation ON peluqueria_turnos FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON peluqueria_turnos TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_peluqueria_org   ON peluqueria_turnos(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_peluqueria_fecha ON peluqueria_turnos(fecha);

-- Autoría automática (creado_por / actualizado_por)
ALTER TABLE peluqueria_turnos ADD COLUMN IF NOT EXISTS creado_por text;
ALTER TABLE peluqueria_turnos ADD COLUMN IF NOT EXISTS actualizado_por text;
DROP TRIGGER IF EXISTS tg_autor ON peluqueria_turnos;
CREATE TRIGGER tg_autor BEFORE INSERT OR UPDATE ON peluqueria_turnos
  FOR EACH ROW EXECUTE FUNCTION tg_set_autor();

-- Porcentaje que le corresponde al peluquero (editable por clínica), default 60%.
ALTER TABLE organizaciones ADD COLUMN IF NOT EXISTS peluqueria_porcentaje numeric(5,2) NOT NULL DEFAULT 60;
