-- ============================================================================
--  MÓDULO VETERINARIA — Recordatorios / Turnos
-- ============================================================================

CREATE TABLE IF NOT EXISTS recordatorios (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint REFERENCES pacientes(id) ON DELETE CASCADE,
  fecha            date NOT NULL,
  tipo             text,
  descripcion      text,
  estado           text NOT NULL DEFAULT 'pendiente',  -- pendiente | hecho
  notas            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON recordatorios;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON recordatorios
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE recordatorios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON recordatorios;
CREATE POLICY org_isolation ON recordatorios FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON recordatorios TO authenticated, service_role;

CREATE INDEX IF NOT EXISTS idx_recordatorios_org      ON recordatorios(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_recordatorios_fecha    ON recordatorios(fecha);
CREATE INDEX IF NOT EXISTS idx_recordatorios_paciente ON recordatorios(paciente_id);
