CREATE TABLE IF NOT EXISTS sala_espera (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint REFERENCES pacientes(id) ON DELETE SET NULL,
  nombre_libre     text,                              -- walk-in sin paciente registrado
  motivo           text,
  prioridad        text NOT NULL DEFAULT 'normal',    -- normal | urgente
  estado           text NOT NULL DEFAULT 'esperando', -- esperando | atendiendo | atendido
  check_in_at      timestamptz NOT NULL DEFAULT now(),
  atendido_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS tg_set_org_id ON sala_espera;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON sala_espera FOR EACH ROW EXECUTE FUNCTION _set_org_id();
ALTER TABLE sala_espera ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON sala_espera;
CREATE POLICY org_isolation ON sala_espera FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id()) WITH CHECK (organizacion_id = get_my_org_id());
GRANT ALL ON sala_espera TO authenticated, service_role;
CREATE INDEX IF NOT EXISTS idx_sala_org ON sala_espera(organizacion_id);
