-- ============================================================================
--  MÓDULO VETERINARIA — Turnos (agenda de citas)
-- ============================================================================
CREATE TABLE IF NOT EXISTS turnos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organizacion_id  uuid REFERENCES organizaciones(id),
  paciente_id      bigint REFERENCES pacientes(id) ON DELETE SET NULL,
  cliente_id       bigint REFERENCES clientes(id)  ON DELETE SET NULL,
  fecha            date NOT NULL,
  hora             time NOT NULL,
  duracion         int  DEFAULT 30,
  tipo             text,
  profesional      text,
  estado           text NOT NULL DEFAULT 'reservado',  -- reservado/confirmado/atendido/ausente/cancelado
  notas            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS tg_set_org_id ON turnos;
CREATE TRIGGER tg_set_org_id BEFORE INSERT ON turnos
  FOR EACH ROW EXECUTE FUNCTION _set_org_id();

ALTER TABLE turnos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS org_isolation ON turnos;
CREATE POLICY org_isolation ON turnos FOR ALL TO authenticated
  USING (organizacion_id = get_my_org_id())
  WITH CHECK (organizacion_id = get_my_org_id());

GRANT ALL ON turnos TO authenticated, service_role;

CREATE INDEX IF NOT EXISTS idx_turnos_org   ON turnos(organizacion_id);
CREATE INDEX IF NOT EXISTS idx_turnos_fecha ON turnos(fecha);
