// ─────────────────────────────────────────────────────────────────────────────
// clone_schema.mjs — Clona el ESQUEMA (sin datos) de un proyecto Supabase a otro.
//
// Uso:
//   node scripts/clone_schema.mjs            → genera clone_schema.generated.sql (revisión)
//   node scripts/clone_schema.mjs --apply    → además lo ejecuta en la base NUEVA
//
// Lee las connection strings desde .dburls.local (NEW=... / OLD=...)
// No requiere Docker ni pg_dump. Introspecta los catálogos de Postgres.
// La protección entre clientes la da RLS; los datos reales NO se copian.
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from "node:fs"
import pg from "pg"

const APPLY = process.argv.includes("--apply")

// ── Leer .dburls.local ──────────────────────────────────────────────────────
const env = Object.fromEntries(
  readFileSync(new URL("../.dburls.local", import.meta.url), "utf8")
    .split(/\r?\n/).filter(Boolean).map(l => {
      const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]
    })
)
if (!env.OLD) { console.error("Falta OLD= en .dburls.local"); process.exit(1) }
if (!env.NEW) { console.error("Falta NEW= en .dburls.local"); process.exit(1) }

const ssl = { rejectUnauthorized: false }

// Normaliza un array de Postgres que pg puede devolver como string '{a,b}'
const pgArray = (v) => {
  if (Array.isArray(v)) return v
  if (v == null) return []
  return v.replace(/^\{|\}$/g, "").split(",").map(s => s.replace(/^"|"$/g, "")).filter(Boolean)
}

const out = []
const push = (s) => out.push(s)
const section = (t) => push(`\n-- ${"═".repeat(70)}\n-- ${t}\n-- ${"═".repeat(70)}`)

const old = new pg.Client({ connectionString: env.OLD, ssl })
await old.connect()
console.log("Conectado a la base ORIGEN. Introspectando esquema public…")

const q = async (sql, params) => (await old.query(sql, params)).rows

push("-- Esquema clonado automáticamente desde el proyecto origen.")
push("-- Generado por scripts/clone_schema.mjs — solo estructura, sin datos.")
push("SET statement_timeout = 0;")
push("SET client_min_messages = warning;")

// ── 1. Extensiones (no del sistema) ─────────────────────────────────────────
section("1. EXTENSIONES")
const exts = await q(
  `SELECT extname FROM pg_extension WHERE extname NOT IN ('plpgsql') ORDER BY extname`
)
for (const e of exts) push(`CREATE EXTENSION IF NOT EXISTS "${e.extname}";`)

// ── 2. Tipos ENUM ───────────────────────────────────────────────────────────
section("2. TIPOS (ENUM)")
const enums = await q(`
  SELECT t.typname,
         array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
  FROM pg_type t
  JOIN pg_enum e ON e.enumtypid = t.oid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
  GROUP BY t.typname ORDER BY t.typname`)
for (const en of enums) {
  const labels = en.labels.map(l => `'${l.replace(/'/g, "''")}'`).join(", ")
  push(`DO $$ BEGIN CREATE TYPE public."${en.typname}" AS ENUM (${labels}); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`)
}

// ── 3. Secuencias ───────────────────────────────────────────────────────────
section("3. SECUENCIAS")
const seqs = await q(`
  SELECT c.relname FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'S' ORDER BY c.relname`)
for (const s of seqs) push(`CREATE SEQUENCE IF NOT EXISTS public."${s.relname}";`)

// ── 4. Tablas (solo columnas) ───────────────────────────────────────────────
section("4. TABLAS (columnas)")
const tables = await q(`
  SELECT c.oid, c.relname FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r' ORDER BY c.relname`)
for (const t of tables) {
  const cols = await q(`
    SELECT a.attname,
           format_type(a.atttypid, a.atttypmod) AS type,
           a.attnotnull, a.attidentity, a.attgenerated,
           pg_get_expr(d.adbin, d.adrelid) AS def
    FROM pg_attribute a
    LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped
    ORDER BY a.attnum`, [t.oid])
  const defs = cols.map(c => {
    let line = `  "${c.attname}" ${c.type}`
    if (c.attidentity === "a") line += " GENERATED ALWAYS AS IDENTITY"
    else if (c.attidentity === "d") line += " GENERATED BY DEFAULT AS IDENTITY"
    else if (c.attgenerated === "s") line += ` GENERATED ALWAYS AS (${c.def}) STORED`
    else if (c.def != null) line += ` DEFAULT ${c.def}`
    if (c.attnotnull) line += " NOT NULL"
    return line
  })
  push(`CREATE TABLE IF NOT EXISTS public."${t.relname}" (\n${defs.join(",\n")}\n);`)
}

// ── 5. Constraints: PK / UNIQUE / CHECK (FK al final) ────────────────────────
section("5. CONSTRAINTS (PK / UNIQUE / CHECK)")
const cons = await q(`
  SELECT c.conname, rel.relname AS tbl, c.contype,
         pg_get_constraintdef(c.oid) AS def
  FROM pg_constraint c
  JOIN pg_class rel ON rel.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace
  WHERE n.nspname = 'public'
  ORDER BY CASE c.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 ELSE 4 END`)
const addCon = (c) =>
  `ALTER TABLE public."${c.tbl}" ADD CONSTRAINT "${c.conname}" ${c.def};`
for (const c of cons.filter(c => c.contype !== "f")) push(addCon(c))

// ── 6. Índices (los que no respaldan un constraint) ─────────────────────────
section("6. ÍNDICES")
const idx = await q(`
  SELECT pg_get_indexdef(i.indexrelid) AS def
  FROM pg_index i
  JOIN pg_class c ON c.oid = i.indrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND i.indexrelid NOT IN (SELECT conindid FROM pg_constraint WHERE conindid <> 0)`)
for (const i of idx) push(i.def + ";")

// ── 7. Funciones / RPCs ─────────────────────────────────────────────────────
section("7. FUNCIONES / RPCs")
const funcs = await q(`
  SELECT pg_get_functiondef(p.oid) AS def
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind IN ('f','p')
  ORDER BY p.proname`)
for (const f of funcs) push(f.def + ";")

// ── 8. Vistas ───────────────────────────────────────────────────────────────
section("8. VISTAS")
const views = await q(`
  SELECT c.relname, pg_get_viewdef(c.oid, true) AS def, c.reloptions, c.relkind
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind IN ('v','m') ORDER BY c.relname`)
for (const v of views) {
  const ro = pgArray(v.reloptions)
  const opts = ro.length ? ` WITH (${ro.join(", ")})` : ""
  const kind = v.relkind === "m" ? "MATERIALIZED VIEW" : "VIEW"
  const orRepl = v.relkind === "m" ? "" : "OR REPLACE "
  push(`CREATE ${orRepl}${kind} public."${v.relname}"${opts} AS\n${v.def}`)
}

// ── 9. Triggers ─────────────────────────────────────────────────────────────
section("9. TRIGGERS")
const trigs = await q(`
  SELECT pg_get_triggerdef(t.oid) AS def
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND NOT t.tgisinternal`)
for (const t of trigs) push(t.def + ";")

// ── 10. Foreign keys (después de que existan todas las tablas) ──────────────
section("10. FOREIGN KEYS")
for (const c of cons.filter(c => c.contype === "f")) push(addCon(c))

// ── 11. Row Level Security ──────────────────────────────────────────────────
section("11. ROW LEVEL SECURITY")
const rls = await q(`
  SELECT c.relname, c.relrowsecurity, c.relforcerowsecurity
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity`)
for (const r of rls) {
  push(`ALTER TABLE public."${r.relname}" ENABLE ROW LEVEL SECURITY;`)
  if (r.relforcerowsecurity) push(`ALTER TABLE public."${r.relname}" FORCE ROW LEVEL SECURITY;`)
}

// ── 12. Políticas RLS ───────────────────────────────────────────────────────
section("12. POLÍTICAS RLS")
const pols = await q(`SELECT * FROM pg_policies WHERE schemaname = 'public'`)
for (const p of pols) {
  const r = pgArray(p.roles)
  const roles = r.length ? r.join(", ") : "public"
  let s = `CREATE POLICY "${p.policyname}" ON public."${p.tablename}"`
  s += ` AS ${p.permissive === "PERMISSIVE" ? "PERMISSIVE" : "RESTRICTIVE"}`
  s += ` FOR ${p.cmd} TO ${roles}`
  if (p.qual != null) s += ` USING (${p.qual})`
  if (p.with_check != null) s += ` WITH CHECK (${p.with_check})`
  push(s + ";")
}

// ── 13. Grants (modelo Supabase: RLS hace el aislamiento real) ──────────────
section("13. GRANTS (roles Supabase)")
push(`GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;`)
push(`GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;`)
push(`GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`)
push(`GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;`)

await old.end()

const sql = out.join("\n") + "\n"
writeFileSync(new URL("../clone_schema.generated.sql", import.meta.url), sql)
console.log(`\nSQL generado: clone_schema.generated.sql`)
console.log(`  Tablas: ${tables.length} | Funciones: ${funcs.length} | Vistas: ${views.length} | Triggers: ${trigs.length} | Políticas: ${pols.length} | Enums: ${enums.length} | Secuencias: ${seqs.length}`)

// ── Aplicar en la base NUEVA ────────────────────────────────────────────────
if (APPLY) {
  console.log("\nAplicando en la base NUEVA…")
  const neu = new pg.Client({ connectionString: env.NEW, ssl })
  await neu.connect()
  try {
    await neu.query("BEGIN")
    await neu.query(sql)
    await neu.query("COMMIT")
    console.log("✅ Esquema aplicado correctamente en la base NUEVA.")
  } catch (e) {
    await neu.query("ROLLBACK").catch(() => {})
    console.error("❌ Error al aplicar (rollback hecho, la base quedó intacta):", e.message)
    process.exitCode = 1
  } finally {
    await neu.end()
  }
} else {
  console.log("\nRevisá el archivo y, si está OK, corré:  node scripts/clone_schema.mjs --apply")
}
